# Generated by Django 5.1.5 on 2025-08-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='numéro de facture')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='sous-total')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='montant TVA')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='montant réduction')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant total')),
                ('billing_address', models.TextField(blank=True, verbose_name='adresse de facturation')),
                ('billing_city', models.CharField(blank=True, max_length=100, verbose_name='ville de facturation')),
                ('billing_country', models.CharField(blank=True, max_length=100, verbose_name='pays de facturation')),
                ('billing_postal_code', models.CharField(blank=True, max_length=20, verbose_name='code postal')),
                ('is_paid', models.BooleanField(default=False, verbose_name='payée')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='payée le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'facture',
                'verbose_name_plural': 'factures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('subscription', 'Abonnement'), ('course', 'Formation'), ('coaching', 'Coaching'), ('donation', 'Don')], default='subscription', max_length=20, verbose_name='type de paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='devise')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('refunded', 'Remboursé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='statut')),
                ('payment_method', models.CharField(choices=[('card', 'Carte bancaire'), ('paypal', 'PayPal'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement bancaire')], default='card', max_length=20, verbose_name='méthode de paiement')),
                ('transaction_id', models.CharField(blank=True, max_length=100, unique=True, verbose_name='ID de transaction')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='réponse de la passerelle')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='terminé le')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('description', models.TextField(verbose_name='description')),
                ('plan_type', models.CharField(choices=[('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('yearly', 'Annuel'), ('lifetime', 'À vie')], default='monthly', max_length=20, verbose_name='type de plan')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Prix avant réduction', max_digits=10, null=True, verbose_name='prix original')),
                ('discount_percentage', models.PositiveIntegerField(default=0, verbose_name='pourcentage de réduction')),
                ('features', models.JSONField(default=list, help_text='Liste des fonctionnalités incluses', verbose_name='fonctionnalités')),
                ('max_courses', models.PositiveIntegerField(default=0, help_text='0 = illimité', verbose_name='nombre maximum de cours')),
                ('max_coaching_sessions', models.PositiveIntegerField(default=0, help_text='0 = illimité', verbose_name='nombre maximum de sessions de coaching')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_popular', models.BooleanField(default=False, verbose_name='populaire')),
                ('is_featured', models.BooleanField(default=False, verbose_name='mis en avant')),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Durée du plan en jours', verbose_name='durée en jours')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': "plan d'abonnement",
                'verbose_name_plural': "plans d'abonnement",
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('expired', 'Expiré'), ('cancelled', 'Annulé'), ('pending', 'En attente'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='statut')),
                ('start_date', models.DateTimeField(verbose_name='date de début')),
                ('end_date', models.DateTimeField(verbose_name='date de fin')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='annulé le')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='renouvellement automatique')),
                ('next_billing_date', models.DateTimeField(blank=True, null=True, verbose_name='prochaine facturation')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant payé')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='méthode de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'abonnement utilisateur',
                'verbose_name_plural': 'abonnements utilisateur',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('coupon_type', models.CharField(choices=[('percentage', 'Pourcentage'), ('fixed', 'Montant fixe')], default='percentage', max_length=20, verbose_name='type de coupon')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valeur de réduction')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, help_text='Montant minimum pour utiliser le coupon', max_digits=10, verbose_name='montant minimum')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = illimité', verbose_name='utilisation maximum')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name="nombre d'utilisations")),
                ('valid_from', models.DateTimeField(verbose_name='valide à partir du')),
                ('valid_until', models.DateTimeField(verbose_name="valide jusqu'au")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('applicable_courses', models.ManyToManyField(blank=True, related_name='coupons', to='courses.course', verbose_name='formations applicables')),
            ],
            options={
                'verbose_name': 'coupon',
                'verbose_name_plural': 'coupons',
                'ordering': ['-created_at'],
            },
        ),
    ]
