# Generated by Django 5.1.5 on 2025-08-23 10:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse email')),
                ('user_type', models.CharField(choices=[('student', 'Étudiant'), ('professional', 'Professionnel'), ('manager', 'Manager'), ('coach', 'Coach'), ('admin', 'Administrateur')], default='student', max_length=20, verbose_name="type d'utilisateur")),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='entreprise')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='poste')),
                ('bio', models.TextField(blank=True, verbose_name='biographie')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='photo de profil')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('address', models.TextField(blank=True, verbose_name='adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='pays')),
                ('communication_level', models.IntegerField(default=1, help_text='Échelle de 1 à 10', verbose_name='niveau de communication')),
                ('leadership_level', models.IntegerField(default=1, help_text='Échelle de 1 à 10', verbose_name='niveau de leadership')),
                ('stress_management_level', models.IntegerField(default=1, help_text='Échelle de 1 à 10', verbose_name='gestion du stress')),
                ('creativity_level', models.IntegerField(default=1, help_text='Échelle de 1 à 10', verbose_name='niveau de créativité')),
                ('emotional_intelligence_level', models.IntegerField(default=1, help_text='Échelle de 1 à 10', verbose_name='intelligence émotionnelle')),
                ('is_subscribed', models.BooleanField(default=False, verbose_name='abonné')),
                ('subscription_start_date', models.DateTimeField(blank=True, null=True, verbose_name="date de début d'abonnement")),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True, verbose_name="date de fin d'abonnement")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='pourcentage de progression')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='commencé le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='terminé le')),
                ('completed_lessons', models.ManyToManyField(blank=True, related_name='completed_by', to='courses.lesson')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'progression utilisateur',
                'verbose_name_plural': 'progressions utilisateur',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
