# Generated by Django 5.1.5 on 2025-08-23 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=200, verbose_name='spécialisation')),
                ('experience_years', models.PositiveIntegerField(verbose_name="années d'expérience")),
                ('bio', models.TextField(verbose_name='biographie')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='tarif horaire')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponible')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='note moyenne')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'coach',
                'verbose_name_plural': 'coachs',
            },
        ),
        migrations.CreateModel(
            name='CoachingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('individual', 'Individuel'), ('group', 'Groupe'), ('assessment', 'Évaluation'), ('follow_up', 'Suivi')], default='individual', max_length=20, verbose_name='type de session')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('scheduled_at', models.DateTimeField(verbose_name='programmée le')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='durée en minutes')),
                ('status', models.CharField(choices=[('scheduled', 'Programmée'), ('confirmed', 'Confirmée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='scheduled', max_length=20, verbose_name='statut')),
                ('meeting_link', models.URLField(blank=True, verbose_name='lien de réunion')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix')),
                ('is_paid', models.BooleanField(default=False, verbose_name='payé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='terminé le')),
            ],
            options={
                'verbose_name': 'session de coaching',
                'verbose_name_plural': 'sessions de coaching',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='note du client')),
                ('client_comment', models.TextField(blank=True, verbose_name='commentaire du client')),
                ('coach_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='note du coach')),
                ('coach_comment', models.TextField(blank=True, verbose_name='commentaire du coach')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': "retour d'expérience",
                'verbose_name_plural': "retours d'expérience",
            },
        ),
    ]
