# Generated by Django 5.1.5 on 2025-08-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='couleur')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'catégorie blog',
                'verbose_name_plural': 'catégories blog',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='contenu')),
                ('is_approved', models.BooleanField(default=False, verbose_name='approuvé')),
                ('is_spam', models.BooleanField(default=False, verbose_name='spam')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'commentaire',
                'verbose_name_plural': 'commentaires',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('excerpt', models.TextField(blank=True, max_length=300, verbose_name='extrait')),
                ('content', models.TextField(verbose_name='contenu')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='description meta')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, verbose_name='mots-clés meta')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='image à la une')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='statut')),
                ('is_featured', models.BooleanField(default=False, verbose_name='mis en avant')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='autoriser les commentaires')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='nombre de vues')),
                ('read_time_minutes', models.PositiveIntegerField(default=5, verbose_name='temps de lecture en minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publié le')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('subject', models.CharField(max_length=200, verbose_name='sujet')),
                ('content', models.TextField(verbose_name='contenu')),
                ('is_sent', models.BooleanField(default=False, verbose_name='envoyé')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='envoyé le')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name="nombre d'envois")),
                ('opened_count', models.PositiveIntegerField(default=0, verbose_name="nombre d'ouvertures")),
                ('clicked_count', models.PositiveIntegerField(default=0, verbose_name='nombre de clics')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'newsletter',
                'verbose_name_plural': 'newsletters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='prénom')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='abonné le')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='désabonné le')),
            ],
            options={
                'verbose_name': 'abonné newsletter',
                'verbose_name_plural': 'abonnés newsletter',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
