# Generated by Django 5.1.5 on 2025-08-23 10:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icône')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='couleur')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='inscrit le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='terminé le')),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='pourcentage de progression')),
            ],
            options={
                'verbose_name': 'inscription',
                'verbose_name_plural': 'inscriptions',
            },
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='note')),
                ('review', models.TextField(blank=True, verbose_name='avis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'évaluation',
                'verbose_name_plural': 'évaluations',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('slug', models.SlugField(max_length=200, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('lesson_type', models.CharField(choices=[('video', 'Vidéo'), ('text', 'Texte'), ('quiz', 'Quiz'), ('exercise', 'Exercice'), ('webinar', 'Webinaire')], default='video', max_length=20, verbose_name='type de leçon')),
                ('content', models.TextField(blank=True, verbose_name='contenu')),
                ('video_url', models.URLField(blank=True, verbose_name='URL vidéo')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='durée en minutes')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='lesson_attachments/', verbose_name='fichier joint')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'leçon',
                'verbose_name_plural': 'leçons',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('short_description', models.CharField(max_length=300, verbose_name='description courte')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], default='beginner', max_length=20, verbose_name='niveau de difficulté')),
                ('duration_hours', models.PositiveIntegerField(verbose_name='durée en heures')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='prix')),
                ('is_free', models.BooleanField(default=False, verbose_name='gratuit')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/', verbose_name='miniature')),
                ('video_intro', models.URLField(blank=True, verbose_name="vidéo d'introduction")),
                ('objectives', models.TextField(verbose_name="objectifs d'apprentissage")),
                ('prerequisites', models.TextField(blank=True, verbose_name='prérequis')),
                ('target_audience', models.TextField(verbose_name='public cible')),
                ('is_published', models.BooleanField(default=False, verbose_name='publié')),
                ('is_featured', models.BooleanField(default=False, verbose_name='mis en avant')),
                ('enrollment_count', models.PositiveIntegerField(default=0, verbose_name="nombre d'inscriptions")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publié le')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.category', verbose_name='catégorie')),
            ],
            options={
                'verbose_name': 'formation',
                'verbose_name_plural': 'formations',
                'ordering': ['-created_at'],
            },
        ),
    ]
