# Generated by Django 5.1.5 on 2025-11-27 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseenrollment_payment_status'),
    ]

    operations = [
    ]
